name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.409
    - name: Restore dependencies
      run: dotnet restore src/Magenta.Workflow.sln
    - name: Build
      run: dotnet build src/Magenta.Workflow.sln --no-restore
    - name: Test
      run: dotnet test src/Magenta.Workflow.Tests/Magenta.Workflow.Tests.csproj --no-build --verbosity normal
